### PR TITLE
Replace JARs with maven dependencies for tagsoup and joda-time

### PR DESCRIPTION
**Pull request by ligi**
this prepares #15 
one jar is left - the guava-compressed - unfortunately this is not an easy replacement as when exchanging for the guava version on maven-central we get over the 64k method limit.
Not yet sure how to deal with this - I don't use guava anymore - when using Kotlin you do not really need it anymore
Also joda-time should be replaced with https://github.com/JakeWharton/ThreeTenABP - even the creator of joda-time advocates for jsr-310 for this case now ;-)

### CODE REVIEW

**Comment by prusnak** [comment]
Thanks!

**Comment by ligi** [comment]
yw.

guava seems only to be a dependency for cgcmn-liban - not really sure what this is yet - when removing it it seems to only be logging stuff - can you give me a pointer?

**Comment by prusnak** [comment]
cgcmn-liban is a library of common helpers written and used by our contractor (who wrote the app) to simplify the work on their applications. I f you think it can be removed/replaced I don't object.

**Comment by ligi** [comment]
thanks for the info  - ye looks like I will remove it - will also make it smaller ;-)

**Comment by ligi** [comment]
digged a bit deeper - not that easy to remove it - would be easier if Kotlin would be an option here - what do you think? Kotlin is now officially supported by google since IO2017

**Comment by prusnak** [comment]
How exactly it would be easier?

**Comment by ligi** [comment]
I reduced the usage of guava in this app to collections/ImmutableList - the easiest would now to replace it with kotlin collections. Anyway things look way nicer in kotlin and is currently the way to go - especially since google made it official.

**Comment by prusnak** [comment]
Okay, if it builds I am ok with that :-)

**Pull request merged**
