### PR TITLE
Remove constraintlayout dependency

### PR DESCRIPTION
**Pull request by ligi**
Not only makes things leaner - but also helps with this issue:
https://f-droid.org/wiki/page/io.trezor.app/lastbuild_8

### CODE REVIEW

**Comment by prusnak** [comment]
How come it does build without this dependency?

**Comment by ligi** [comment]
I think the original author tried it out and forgot to remove the dependency. Hard to say as the history there always ends up in "import source" for me ..-)
Should have searched for unused dependencies/dead-code a bit longer - I think there is still a lot left - but I stopped when i was below the 65k method limit :wink: Wanted to continue with WALLETH - want to get this new version out: http://walleth.org/2017/06/12/offline-transactions/

**Comment by prusnak** [comment]
> I think the original author tried it out and forgot to remove the dependency. 

Makes sense :-) Thanks

**Comment by ligi** [comment]
You are very welcome - FYI: for f-droid to pick this up you would need to set a new tag

**Pull request merged**
