### PR TITLE
Add gradle witness build-plugin and library whitelists - closes #16

### LINKED ISSUE #16: Add gradle-witness
As this is security-relevant software it should use:

https://github.com/WhisperSystems/gradle-witness

I can PR it if wanted

### PR DESCRIPTION
**Pull request by ligi**
WIP - please do not merge yet

### CODE REVIEW

**Comment by prusnak** [comment]
Quis custodiet ipsos custodes?

How do I know that embedded `libs/gradle-witness.jar` is not malicious and matches the hash from the upsteam?

**Comment by ligi** [comment]
good point - Ideally you generate `libs/gradle-witness.jar` - please read "Using Witness" @: https://github.com/WhisperSystems/gradle-witness

**Comment by ligi** [comment]
So - would be ready from my side now - reoved the WIP - feel free to compile the gradle-witness.jar for yourself before merging

**Comment by prusnak** [comment]
Thanks!

**Pull request merged**
